version: '2'
services:
  npm:
    image: node
    entrypoint: npm
    working_dir: /home/app
    volumes:
      - .:/home/app
  dataset:
    build: .
    image: dataset-cache
    entrypoint: node cli.js
    working_dir: /home/app
    environment:
      - DEBUG=$DEBUG
    volumes:
      - .:/home/app
      - /tmp:/tmp
  test:
    image: dataset-cache
    entrypoint: npm test
    environment:
      - DEBUG=$DEBUG
